spring.application.name=Programski-Jezici
spring.datasource.url=jdbc:mysql://localhost:3309/barcelona_app
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
